// <auto-generated />
using System;
using Kursach_Jewelry.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kursach_Jewelry.Migrations
{
    [DbContext(typeof(DbContextJewelry))]
    [Migration("20231227075049_boba")]
    partial class boba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kursach_Jewelry.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderClient")
                        .HasColumnType("int");

                    b.Property<string>("PhoneClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Master", b =>
                {
                    b.Property<int>("IdMaster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameMaster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderMaster")
                        .HasColumnType("int");

                    b.Property<string>("PhoneMaster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaster");

                    b.ToTable("masters");
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Material", b =>
                {
                    b.Property<int>("IdMaterials")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleMaterial")
                        .HasColumnType("int");

                    b.HasKey("IdMaterials");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("CountOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasterOrder")
                        .HasColumnType("int");

                    b.Property<int>("OrderCost")
                        .HasColumnType("int");

                    b.Property<int>("ProductsID")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("ClientID");

                    b.HasIndex("MasterOrder");

                    b.HasIndex("ProductsID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Product", b =>
                {
                    b.Property<int>("IDProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountProduct")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceProduct")
                        .HasColumnType("int");

                    b.Property<string>("TypeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProducts");

                    b.HasIndex("MaterialID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Order", b =>
                {
                    b.HasOne("Kursach_Jewelry.Models.Client", "client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kursach_Jewelry.Models.Master", "master")
                        .WithMany("Orders")
                        .HasForeignKey("MasterOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kursach_Jewelry.Models.Product", "product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kursach_Jewelry.Models.Product", b =>
                {
                    b.HasOne("Kursach_Jewelry.Models.Material", "Material")
                        .WithMany("product")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
